"""Literature-extracted hydrogel–chondrocyte records.

Scores that papers did not report as a 0–100 index are mapped from quantitative
assays or qualitative descriptions. Mapped fields are listed in `imputed_fields`.

Mapping convention
------------------
viability_pct          live/dead % when reported, else ~90–95 if "high viability"
proliferation_score    relative DNA / cell density vs the paper's own range
differentiation_score  COL2A1 / SOX9 / round morphology / redifferentiation
ecm_deposition_score   sGAG, collagen II, safranin-O / alcian blue relative to
                       the paper's best group (~80–90) and worst (~20–40)
"""

from __future__ import annotations

LITERATURE_RECORDS: list[dict] = [
    # Li et al. 2016, Polymers. GelMA stiffness series, bovine P2, 14 d.
    {
        "record_id": "lit-li2016-gelma-3p8",
        "source": "literature",
        "citation": "Li et al., Polymers 2016",
        "doi": "10.3390/polym8080269",
        "year": 2016,
        "material_class": "GelMA",
        "crosslinking": "photocrosslink",
        "polymer_concentration_wt_pct": 10.0,
        "stiffness_kpa": 3.8,
        "porosity_pct": 88.0,
        "degradation_half_life_days": 8.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "bovine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 14.0,
        "cell_density_million_per_ml": 20.0,
        "passage": 2,
        "viability_pct": 93.0,
        "proliferation_score": 52.0,
        "differentiation_score": 38.0,
        "ecm_deposition_score": 32.0,
        "imputed_fields": [
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
            "porosity_pct",
            "degradation_half_life_days",
        ],
        "notes": "Low stiffness: elongated morphology, weak safranin-O, DNA similar across groups.",
    },
    {
        "record_id": "lit-li2016-gelma-17p1",
        "source": "literature",
        "citation": "Li et al., Polymers 2016",
        "doi": "10.3390/polym8080269",
        "year": 2016,
        "material_class": "GelMA",
        "crosslinking": "photocrosslink",
        "polymer_concentration_wt_pct": 10.0,
        "stiffness_kpa": 17.1,
        "porosity_pct": 82.0,
        "degradation_half_life_days": 14.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "bovine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 14.0,
        "cell_density_million_per_ml": 20.0,
        "passage": 2,
        "viability_pct": 93.0,
        "proliferation_score": 52.0,
        "differentiation_score": 58.0,
        "ecm_deposition_score": 50.0,
        "imputed_fields": [
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
            "porosity_pct",
            "degradation_half_life_days",
        ],
        "notes": "Medium stiffness: mixed morphology, partial proteoglycan staining.",
    },
    {
        "record_id": "lit-li2016-gelma-29p9",
        "source": "literature",
        "citation": "Li et al., Polymers 2016",
        "doi": "10.3390/polym8080269",
        "year": 2016,
        "material_class": "GelMA",
        "crosslinking": "photocrosslink",
        "polymer_concentration_wt_pct": 10.0,
        "stiffness_kpa": 29.9,
        "porosity_pct": 78.0,
        "degradation_half_life_days": 21.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "bovine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 14.0,
        "cell_density_million_per_ml": 20.0,
        "passage": 2,
        "viability_pct": 93.0,
        "proliferation_score": 52.0,
        "differentiation_score": 82.0,
        "ecm_deposition_score": 80.0,
        "imputed_fields": [
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
            "porosity_pct",
            "degradation_half_life_days",
        ],
        "notes": "High stiffness best for round morphology, sGAG/DNA, Col2a1 and aggrecan.",
    },
    # Bachmann et al. 2020, Front Bioeng Biotechnol. Fibrin / silk-fibrin / PEG-dextran.
    {
        "record_id": "lit-bachmann2020-fibrin-1-tgf",
        "source": "literature",
        "citation": "Bachmann et al., Front. Bioeng. Biotechnol. 2020",
        "doi": "10.3389/fbioe.2020.00373",
        "year": 2020,
        "material_class": "fibrin",
        "crosslinking": "enzymatic",
        "polymer_concentration_wt_pct": 1.2,
        "stiffness_kpa": 1.0,
        "porosity_pct": 92.0,
        "degradation_half_life_days": 6.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "TGF_b3",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 1.0,
        "passage": 2,
        "viability_pct": 92.0,
        "proliferation_score": 70.0,
        "differentiation_score": 42.0,
        "ecm_deposition_score": 40.0,
        "imputed_fields": [
            "polymer_concentration_wt_pct",
            "porosity_pct",
            "degradation_half_life_days",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Soft fibrin + TGF-β3: high viability, fibroblastic morphology, diffuse sGAG.",
    },
    {
        "record_id": "lit-bachmann2020-fibrin-15-tgf",
        "source": "literature",
        "citation": "Bachmann et al., Front. Bioeng. Biotechnol. 2020",
        "doi": "10.3389/fbioe.2020.00373",
        "year": 2020,
        "material_class": "fibrin",
        "crosslinking": "enzymatic",
        "polymer_concentration_wt_pct": 2.4,
        "stiffness_kpa": 15.0,
        "porosity_pct": 86.0,
        "degradation_half_life_days": 10.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "TGF_b3",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 1.0,
        "passage": 2,
        "viability_pct": 96.0,
        "proliferation_score": 62.0,
        "differentiation_score": 64.0,
        "ecm_deposition_score": 62.0,
        "imputed_fields": [
            "polymer_concentration_wt_pct",
            "porosity_pct",
            "degradation_half_life_days",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Intermediate fibrin stiffness; mixed morphology.",
    },
    {
        "record_id": "lit-bachmann2020-fibrin-30-tgf",
        "source": "literature",
        "citation": "Bachmann et al., Front. Bioeng. Biotechnol. 2020",
        "doi": "10.3389/fbioe.2020.00373",
        "year": 2020,
        "material_class": "fibrin",
        "crosslinking": "enzymatic",
        "polymer_concentration_wt_pct": 3.5,
        "stiffness_kpa": 30.0,
        "porosity_pct": 80.0,
        "degradation_half_life_days": 14.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "TGF_b3",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 1.0,
        "passage": 2,
        "viability_pct": 99.0,
        "proliferation_score": 58.0,
        "differentiation_score": 88.0,
        "ecm_deposition_score": 90.0,
        "imputed_fields": [
            "polymer_concentration_wt_pct",
            "porosity_pct",
            "degradation_half_life_days",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "30 kPa fibrin + TGF-β3: best redifferentiation, chondron-like sGAG halos, collagen II.",
    },
    {
        "record_id": "lit-bachmann2020-fibrin-30-notgf",
        "source": "literature",
        "citation": "Bachmann et al., Front. Bioeng. Biotechnol. 2020",
        "doi": "10.3389/fbioe.2020.00373",
        "year": 2020,
        "material_class": "fibrin",
        "crosslinking": "enzymatic",
        "polymer_concentration_wt_pct": 3.5,
        "stiffness_kpa": 30.0,
        "porosity_pct": 80.0,
        "degradation_half_life_days": 14.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 1.0,
        "passage": 2,
        "viability_pct": 97.0,
        "proliferation_score": 50.0,
        "differentiation_score": 70.0,
        "ecm_deposition_score": 68.0,
        "imputed_fields": [
            "polymer_concentration_wt_pct",
            "porosity_pct",
            "degradation_half_life_days",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "30 kPa fibrin without TGF-β3 still supports spherical morphology; less ECM than +TGF.",
    },
    {
        "record_id": "lit-bachmann2020-silkfibrin-1-tgf",
        "source": "literature",
        "citation": "Bachmann et al., Front. Bioeng. Biotechnol. 2020",
        "doi": "10.3389/fbioe.2020.00373",
        "year": 2020,
        "material_class": "silk_fibrin",
        "crosslinking": "enzymatic",
        "polymer_concentration_wt_pct": 2.0,
        "stiffness_kpa": 1.0,
        "porosity_pct": 90.0,
        "degradation_half_life_days": 12.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "TGF_b3",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 1.0,
        "passage": 2,
        "viability_pct": 89.0,
        "proliferation_score": 66.0,
        "differentiation_score": 44.0,
        "ecm_deposition_score": 42.0,
        "imputed_fields": [
            "polymer_concentration_wt_pct",
            "porosity_pct",
            "degradation_half_life_days",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Soft silk/fibrin + TGF: high viability, fibroblastic morphology.",
    },
    {
        "record_id": "lit-bachmann2020-silkfibrin-30-tgf",
        "source": "literature",
        "citation": "Bachmann et al., Front. Bioeng. Biotechnol. 2020",
        "doi": "10.3389/fbioe.2020.00373",
        "year": 2020,
        "material_class": "silk_fibrin",
        "crosslinking": "enzymatic",
        "polymer_concentration_wt_pct": 4.0,
        "stiffness_kpa": 30.0,
        "porosity_pct": 78.0,
        "degradation_half_life_days": 21.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "TGF_b3",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 1.0,
        "passage": 2,
        "viability_pct": 98.0,
        "proliferation_score": 55.0,
        "differentiation_score": 86.0,
        "ecm_deposition_score": 88.0,
        "imputed_fields": [
            "polymer_concentration_wt_pct",
            "porosity_pct",
            "degradation_half_life_days",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "30 kPa silk/fibrin + TGF: chondron-like clusters, strong collagen II.",
    },
    {
        "record_id": "lit-bachmann2020-pegdex-1",
        "source": "literature",
        "citation": "Bachmann et al., Front. Bioeng. Biotechnol. 2020",
        "doi": "10.3389/fbioe.2020.00373",
        "year": 2020,
        "material_class": "PEG_dextran",
        "crosslinking": "chemical",
        "polymer_concentration_wt_pct": 4.0,
        "stiffness_kpa": 1.0,
        "porosity_pct": 70.0,
        "degradation_half_life_days": 180.0,
        "surface_chemistry": "none",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 1.0,
        "passage": 2,
        "viability_pct": 67.0,
        "proliferation_score": 22.0,
        "differentiation_score": 18.0,
        "ecm_deposition_score": 12.0,
        "imputed_fields": [
            "polymer_concentration_wt_pct",
            "porosity_pct",
            "degradation_half_life_days",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Bioinert PEG-dextran 1 kPa: viability 67%, poor ECM.",
    },
    {
        "record_id": "lit-bachmann2020-pegdex-30",
        "source": "literature",
        "citation": "Bachmann et al., Front. Bioeng. Biotechnol. 2020",
        "doi": "10.3389/fbioe.2020.00373",
        "year": 2020,
        "material_class": "PEG_dextran",
        "crosslinking": "chemical",
        "polymer_concentration_wt_pct": 10.0,
        "stiffness_kpa": 30.0,
        "porosity_pct": 45.0,
        "degradation_half_life_days": 300.0,
        "surface_chemistry": "none",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 1.0,
        "passage": 2,
        "viability_pct": 5.0,
        "proliferation_score": 5.0,
        "differentiation_score": 5.0,
        "ecm_deposition_score": 4.0,
        "imputed_fields": [
            "polymer_concentration_wt_pct",
            "porosity_pct",
            "degradation_half_life_days",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "PEG-dextran 30 kPa: no measurable viability (pore size / motility restriction).",
    },
    # Zhang et al. 2024 gelatin–alginate bioprinted scaffolds.
    {
        "record_id": "lit-zhang2024-gelalg-low",
        "source": "literature",
        "citation": "Zhang et al., Front. Mater. 2024",
        "doi": "10.3389/fmats.2024.1501505",
        "year": 2024,
        "material_class": "gelatin_alginate",
        "crosslinking": "ionic",
        "polymer_concentration_wt_pct": 6.0,
        "stiffness_kpa": 8.0,
        "porosity_pct": 85.0,
        "degradation_half_life_days": 10.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_bioprint",
        "growth_factor": "none",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 5.0,
        "passage": 2,
        "viability_pct": 93.24,
        "proliferation_score": 68.0,
        "differentiation_score": 78.0,
        "ecm_deposition_score": 72.0,
        "imputed_fields": [
            "stiffness_kpa",
            "porosity_pct",
            "degradation_half_life_days",
            "cell_density_million_per_ml",
            "passage",
            "species",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Low concentration: viability 93.24%, high SOX9/Agg/Col2 vs high-concentration group.",
    },
    {
        "record_id": "lit-zhang2024-gelalg-med",
        "source": "literature",
        "citation": "Zhang et al., Front. Mater. 2024",
        "doi": "10.3389/fmats.2024.1501505",
        "year": 2024,
        "material_class": "gelatin_alginate",
        "crosslinking": "ionic",
        "polymer_concentration_wt_pct": 9.0,
        "stiffness_kpa": 18.0,
        "porosity_pct": 78.0,
        "degradation_half_life_days": 16.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_bioprint",
        "growth_factor": "none",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 5.0,
        "passage": 2,
        "viability_pct": 92.04,
        "proliferation_score": 72.0,
        "differentiation_score": 80.0,
        "ecm_deposition_score": 76.0,
        "imputed_fields": [
            "stiffness_kpa",
            "porosity_pct",
            "degradation_half_life_days",
            "cell_density_million_per_ml",
            "passage",
            "species",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Medium concentration: best chondrosphere formation, high chondrogenic genes.",
    },
    {
        "record_id": "lit-zhang2024-gelalg-high",
        "source": "literature",
        "citation": "Zhang et al., Front. Mater. 2024",
        "doi": "10.3389/fmats.2024.1501505",
        "year": 2024,
        "material_class": "gelatin_alginate",
        "crosslinking": "ionic",
        "polymer_concentration_wt_pct": 12.0,
        "stiffness_kpa": 32.0,
        "porosity_pct": 68.0,
        "degradation_half_life_days": 24.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_bioprint",
        "growth_factor": "none",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 5.0,
        "passage": 2,
        "viability_pct": 88.46,
        "proliferation_score": 48.0,
        "differentiation_score": 52.0,
        "ecm_deposition_score": 50.0,
        "imputed_fields": [
            "stiffness_kpa",
            "porosity_pct",
            "degradation_half_life_days",
            "cell_density_million_per_ml",
            "passage",
            "species",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "High concentration: viability 88.46%, significantly lower SOX9/Agg/Col2.",
    },
    # DeKosky / PEG–agarose IPN, Tissue Eng Part A 2010.
    {
        "record_id": "lit-dekosky2010-agarose",
        "source": "literature",
        "citation": "DeKosky et al., Tissue Eng. Part A 2010",
        "doi": "10.1089/ten.tea.2010.0159",
        "year": 2010,
        "material_class": "agarose",
        "crosslinking": "thermal",
        "polymer_concentration_wt_pct": 2.0,
        "stiffness_kpa": 28.0,
        "porosity_pct": 84.0,
        "degradation_half_life_days": 120.0,
        "surface_chemistry": "none",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "bovine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 10.0,
        "passage": 2,
        "viability_pct": 86.0,
        "proliferation_score": 35.0,
        "differentiation_score": 72.0,
        "ecm_deposition_score": 70.0,
        "imputed_fields": [
            "porosity_pct",
            "degradation_half_life_days",
            "cell_density_million_per_ml",
            "passage",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Agarose: low adhesion, round cells, GAG synthesis reference for IPN comparison.",
    },
    {
        "record_id": "lit-dekosky2010-peg",
        "source": "literature",
        "citation": "DeKosky et al., Tissue Eng. Part A 2010",
        "doi": "10.1089/ten.tea.2010.0159",
        "year": 2010,
        "material_class": "PEG",
        "crosslinking": "photocrosslink",
        "polymer_concentration_wt_pct": 10.0,
        "stiffness_kpa": 36.0,
        "porosity_pct": 72.0,
        "degradation_half_life_days": 90.0,
        "surface_chemistry": "none",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "bovine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 10.0,
        "passage": 2,
        "viability_pct": 82.0,
        "proliferation_score": 32.0,
        "differentiation_score": 60.0,
        "ecm_deposition_score": 58.0,
        "imputed_fields": [
            "porosity_pct",
            "degradation_half_life_days",
            "cell_density_million_per_ml",
            "passage",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "PEG-DA: higher failure strain than agarose, moderate GAG vs agarose.",
    },
    {
        "record_id": "lit-dekosky2010-ipn",
        "source": "literature",
        "citation": "DeKosky et al., Tissue Eng. Part A 2010",
        "doi": "10.1089/ten.tea.2010.0159",
        "year": 2010,
        "material_class": "PEG",
        "crosslinking": "photocrosslink",
        "polymer_concentration_wt_pct": 12.0,
        "stiffness_kpa": 100.0,
        "porosity_pct": 65.0,
        "degradation_half_life_days": 80.0,
        "surface_chemistry": "none",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "bovine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 10.0,
        "passage": 2,
        "viability_pct": 80.0,
        "proliferation_score": 30.0,
        "differentiation_score": 68.0,
        "ecm_deposition_score": 68.0,
        "imputed_fields": [
            "porosity_pct",
            "degradation_half_life_days",
            "cell_density_million_per_ml",
            "passage",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Agarose/PEG IPN Young's modulus ~149 kPa acellular / ~100 kPa with cells; GAG comparable to agarose.",
    },
    # Schuh et al. 2012 agarose stiffness, J Biomed Mater Res A.
    {
        "record_id": "lit-schuh2012-agarose-soft",
        "source": "literature",
        "citation": "Schuh et al., 2012 (as summarized in Bachmann 2020 Table 1)",
        "doi": "10.1002/jbm.a.33250",
        "year": 2012,
        "material_class": "agarose",
        "crosslinking": "thermal",
        "polymer_concentration_wt_pct": 0.75,
        "stiffness_kpa": 3.7,
        "porosity_pct": 94.0,
        "degradation_half_life_days": 150.0,
        "surface_chemistry": "none",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "porcine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 14.0,
        "cell_density_million_per_ml": 0.6,
        "passage": 2,
        "viability_pct": 90.0,
        "proliferation_score": 72.0,
        "differentiation_score": 60.0,
        "ecm_deposition_score": 58.0,
        "imputed_fields": [
            "porosity_pct",
            "degradation_half_life_days",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Softer agarose: increased proliferation, little phenotype effect vs stiff gel.",
    },
    {
        "record_id": "lit-schuh2012-agarose-stiff",
        "source": "literature",
        "citation": "Schuh et al., 2012 (as summarized in Bachmann 2020 Table 1)",
        "doi": "10.1002/jbm.a.33250",
        "year": 2012,
        "material_class": "agarose",
        "crosslinking": "thermal",
        "polymer_concentration_wt_pct": 3.5,
        "stiffness_kpa": 53.2,
        "porosity_pct": 80.0,
        "degradation_half_life_days": 180.0,
        "surface_chemistry": "none",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "porcine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 14.0,
        "cell_density_million_per_ml": 0.6,
        "passage": 2,
        "viability_pct": 88.0,
        "proliferation_score": 40.0,
        "differentiation_score": 62.0,
        "ecm_deposition_score": 60.0,
        "imputed_fields": [
            "porosity_pct",
            "degradation_half_life_days",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Stiffer agarose: lower proliferation, phenotype similar to soft gel.",
    },
    # Thomas et al. 2017 chitosan–HA dialdehyde.
    {
        "record_id": "lit-thomas2017-chitosan-soft",
        "source": "literature",
        "citation": "Thomas et al., Int. J. Biol. Macromol. 2017",
        "doi": "10.1016/j.ijbiomac.2017.05.116",
        "year": 2017,
        "material_class": "chitosan_HA",
        "crosslinking": "chemical",
        "polymer_concentration_wt_pct": 2.5,
        "stiffness_kpa": 130.8,
        "porosity_pct": 74.0,
        "degradation_half_life_days": 28.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 0.5,
        "cell_type": "articular_chondrocyte",
        "species": "rabbit",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 28.0,
        "cell_density_million_per_ml": 5.0,
        "passage": 3,
        "viability_pct": 82.0,
        "proliferation_score": 48.0,
        "differentiation_score": 58.0,
        "ecm_deposition_score": 55.0,
        "imputed_fields": [
            "porosity_pct",
            "degradation_half_life_days",
            "passage",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Lower-stiffness chitosan-HA in the paper's series; less spherical than stiffer gels.",
    },
    {
        "record_id": "lit-thomas2017-chitosan-stiff",
        "source": "literature",
        "citation": "Thomas et al., Int. J. Biol. Macromol. 2017",
        "doi": "10.1016/j.ijbiomac.2017.05.116",
        "year": 2017,
        "material_class": "chitosan_HA",
        "crosslinking": "chemical",
        "polymer_concentration_wt_pct": 3.5,
        "stiffness_kpa": 199.4,
        "porosity_pct": 68.0,
        "degradation_half_life_days": 35.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 0.5,
        "cell_type": "articular_chondrocyte",
        "species": "rabbit",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 28.0,
        "cell_density_million_per_ml": 5.0,
        "passage": 3,
        "viability_pct": 80.0,
        "proliferation_score": 42.0,
        "differentiation_score": 74.0,
        "ecm_deposition_score": 76.0,
        "imputed_fields": [
            "porosity_pct",
            "degradation_half_life_days",
            "passage",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Stiffer chitosan-HA: spherical morphology and increased matrix synthesis.",
    },
    # Bryant & Anseth 2004 degrading PEG.
    {
        "record_id": "lit-bryant2004-peg-10",
        "source": "literature",
        "citation": "Bryant et al., Biotechnol. Bioeng. 2004",
        "doi": "10.1002/bit.20160",
        "year": 2004,
        "material_class": "PEG",
        "crosslinking": "photocrosslink",
        "polymer_concentration_wt_pct": 10.0,
        "stiffness_kpa": 60.0,
        "porosity_pct": 76.0,
        "degradation_half_life_days": 21.0,
        "surface_chemistry": "MMP_degradable",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "bovine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 28.0,
        "cell_density_million_per_ml": 50.0,
        "passage": 1,
        "viability_pct": 85.0,
        "proliferation_score": 40.0,
        "differentiation_score": 70.0,
        "ecm_deposition_score": 72.0,
        "imputed_fields": [
            "porosity_pct",
            "cell_density_million_per_ml",
            "passage",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "10% degrading PEG, compressive modulus ~60 kPa; GAG and collagen produced.",
    },
    {
        "record_id": "lit-bryant2004-peg-15",
        "source": "literature",
        "citation": "Bryant et al., Biotechnol. Bioeng. 2004",
        "doi": "10.1002/bit.20160",
        "year": 2004,
        "material_class": "PEG",
        "crosslinking": "photocrosslink",
        "polymer_concentration_wt_pct": 15.0,
        "stiffness_kpa": 180.0,
        "porosity_pct": 68.0,
        "degradation_half_life_days": 18.0,
        "surface_chemistry": "MMP_degradable",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "bovine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 28.0,
        "cell_density_million_per_ml": 50.0,
        "passage": 1,
        "viability_pct": 82.0,
        "proliferation_score": 36.0,
        "differentiation_score": 74.0,
        "ecm_deposition_score": 78.0,
        "imputed_fields": [
            "porosity_pct",
            "cell_density_million_per_ml",
            "passage",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "15% macromer: mass loss best matched tissue secretion.",
    },
    {
        "record_id": "lit-bryant2004-peg-20",
        "source": "literature",
        "citation": "Bryant et al., Biotechnol. Bioeng. 2004",
        "doi": "10.1002/bit.20160",
        "year": 2004,
        "material_class": "PEG",
        "crosslinking": "photocrosslink",
        "polymer_concentration_wt_pct": 20.0,
        "stiffness_kpa": 500.0,
        "porosity_pct": 55.0,
        "degradation_half_life_days": 16.0,
        "surface_chemistry": "MMP_degradable",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "bovine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 28.0,
        "cell_density_million_per_ml": 50.0,
        "passage": 1,
        "viability_pct": 78.0,
        "proliferation_score": 28.0,
        "differentiation_score": 66.0,
        "ecm_deposition_score": 70.0,
        "imputed_fields": [
            "porosity_pct",
            "cell_density_million_per_ml",
            "passage",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "20% macromer: initial modulus ~500 kPa; ECM still produced because gels degrade.",
    },
    # Sridhar / Anseth 2015 cellularly degradable PEG + TGF.
    {
        "record_id": "lit-sridhar2015-peg-mmp",
        "source": "literature",
        "citation": "Sridhar et al., Adv. Healthcare Mater. 2015",
        "doi": "10.1002/adhm.201400695",
        "year": 2015,
        "material_class": "PEG",
        "crosslinking": "chemical",
        "polymer_concentration_wt_pct": 10.0,
        "stiffness_kpa": 40.0,
        "porosity_pct": 74.0,
        "degradation_half_life_days": 12.0,
        "surface_chemistry": "MMP_degradable",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "TGF_b1",
        "culture_time_days": 14.0,
        "cell_density_million_per_ml": 20.0,
        "passage": 2,
        "viability_pct": 90.0,
        "proliferation_score": 45.0,
        "differentiation_score": 80.0,
        "ecm_deposition_score": 84.0,
        "imputed_fields": [
            "stiffness_kpa",
            "porosity_pct",
            "degradation_half_life_days",
            "cell_density_million_per_ml",
            "passage",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "MMP-degradable PEG-norbornene + tethered TGF-β1: higher GAG/collagen vs non-degradable.",
    },
    {
        "record_id": "lit-sridhar2015-peg-nondeg",
        "source": "literature",
        "citation": "Sridhar et al., Adv. Healthcare Mater. 2015",
        "doi": "10.1002/adhm.201400695",
        "year": 2015,
        "material_class": "PEG",
        "crosslinking": "chemical",
        "polymer_concentration_wt_pct": 10.0,
        "stiffness_kpa": 45.0,
        "porosity_pct": 72.0,
        "degradation_half_life_days": 200.0,
        "surface_chemistry": "none",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "TGF_b1",
        "culture_time_days": 14.0,
        "cell_density_million_per_ml": 20.0,
        "passage": 2,
        "viability_pct": 88.0,
        "proliferation_score": 38.0,
        "differentiation_score": 62.0,
        "ecm_deposition_score": 55.0,
        "imputed_fields": [
            "stiffness_kpa",
            "porosity_pct",
            "degradation_half_life_days",
            "cell_density_million_per_ml",
            "passage",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Non-degradable PEG control: high viability, less distributed ECM.",
    },
    # Appelman / Lutolf 2010 alginate vs PEG, Soft Matter.
    {
        "record_id": "lit-appelman2011-alginate",
        "source": "literature",
        "citation": "Appelman et al., Soft Matter 2011",
        "doi": "10.1039/c0sm00229a",
        "year": 2011,
        "material_class": "alginate",
        "crosslinking": "ionic",
        "polymer_concentration_wt_pct": 1.5,
        "stiffness_kpa": 12.0,
        "porosity_pct": 90.0,
        "degradation_half_life_days": 40.0,
        "surface_chemistry": "none",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 84.0,
        "cell_density_million_per_ml": 8.0,
        "passage": 2,
        "viability_pct": 88.0,
        "proliferation_score": 34.0,
        "differentiation_score": 88.0,
        "ecm_deposition_score": 80.0,
        "imputed_fields": [
            "stiffness_kpa",
            "porosity_pct",
            "degradation_half_life_days",
            "cell_density_million_per_ml",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Alginate: round morphology, COL2A1/aggrecan up to ~90-fold vs PEG in the paper.",
    },
    {
        "record_id": "lit-appelman2011-peg-2p5",
        "source": "literature",
        "citation": "Appelman et al., Soft Matter 2011",
        "doi": "10.1039/c0sm00229a",
        "year": 2011,
        "material_class": "PEG",
        "crosslinking": "enzymatic",
        "polymer_concentration_wt_pct": 2.5,
        "stiffness_kpa": 8.0,
        "porosity_pct": 88.0,
        "degradation_half_life_days": 25.0,
        "surface_chemistry": "MMP_degradable",
        "has_adhesion_ligand": 0.0,
        "cell_type": "articular_chondrocyte",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 84.0,
        "cell_density_million_per_ml": 8.0,
        "passage": 2,
        "viability_pct": 86.0,
        "proliferation_score": 50.0,
        "differentiation_score": 55.0,
        "ecm_deposition_score": 60.0,
        "imputed_fields": [
            "stiffness_kpa",
            "porosity_pct",
            "degradation_half_life_days",
            "cell_density_million_per_ml",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "2.5% MMP-sensitive PEG: cells spread, lower COL2 vs alginate, higher modulus at 12 weeks.",
    },
    # HA hydrogel MSC/chondrocyte design — Burdick 2011 case study, typical articular HA gel.
    {
        "record_id": "lit-chung2009-ha-fast",
        "source": "literature",
        "citation": "Chung et al., Biomaterials 2009 (HA degradation; Burdick group)",
        "doi": "10.1016/j.biomaterials.2009.04.040",
        "year": 2009,
        "material_class": "HA",
        "crosslinking": "photocrosslink",
        "polymer_concentration_wt_pct": 2.0,
        "stiffness_kpa": 6.0,
        "porosity_pct": 90.0,
        "degradation_half_life_days": 7.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 0.7,
        "cell_type": "MSC",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "TGF_b3",
        "culture_time_days": 14.0,
        "cell_density_million_per_ml": 20.0,
        "passage": 3,
        "viability_pct": 90.0,
        "proliferation_score": 58.0,
        "differentiation_score": 64.0,
        "ecm_deposition_score": 60.0,
        "imputed_fields": [
            "stiffness_kpa",
            "porosity_pct",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Faster-degrading HA: more distributed matrix; MSCs rather than chondrocytes.",
    },
    {
        "record_id": "lit-chung2009-ha-slow",
        "source": "literature",
        "citation": "Chung et al., Biomaterials 2009 (HA degradation; Burdick group)",
        "doi": "10.1016/j.biomaterials.2009.04.040",
        "year": 2009,
        "material_class": "HA",
        "crosslinking": "photocrosslink",
        "polymer_concentration_wt_pct": 5.0,
        "stiffness_kpa": 22.0,
        "porosity_pct": 80.0,
        "degradation_half_life_days": 28.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 0.7,
        "cell_type": "MSC",
        "species": "human",
        "culture_model": "3D_encapsulation",
        "growth_factor": "TGF_b3",
        "culture_time_days": 14.0,
        "cell_density_million_per_ml": 20.0,
        "passage": 3,
        "viability_pct": 88.0,
        "proliferation_score": 46.0,
        "differentiation_score": 76.0,
        "ecm_deposition_score": 74.0,
        "imputed_fields": [
            "stiffness_kpa",
            "porosity_pct",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Slower-degrading HA: more neocartilage matrix by MSCs with TGF-β3.",
    },
    {
        "record_id": "lit-kisiday2002-peptide",
        "source": "literature",
        "citation": "Kisiday et al., PNAS 2002 (self-assembling peptide hydrogel)",
        "doi": "10.1073/pnas.142309999",
        "year": 2002,
        "material_class": "collagen",
        "crosslinking": "ionic",
        "polymer_concentration_wt_pct": 0.5,
        "stiffness_kpa": 5.0,
        "porosity_pct": 95.0,
        "degradation_half_life_days": 20.0,
        "surface_chemistry": "native",
        "has_adhesion_ligand": 1.0,
        "cell_type": "articular_chondrocyte",
        "species": "bovine",
        "culture_model": "3D_encapsulation",
        "growth_factor": "none",
        "culture_time_days": 21.0,
        "cell_density_million_per_ml": 15.0,
        "passage": 0,
        "viability_pct": 91.0,
        "proliferation_score": 64.0,
        "differentiation_score": 75.0,
        "ecm_deposition_score": 73.0,
        "imputed_fields": [
            "stiffness_kpa",
            "porosity_pct",
            "degradation_half_life_days",
            "viability_pct",
            "proliferation_score",
            "differentiation_score",
            "ecm_deposition_score",
        ],
        "notes": "Self-assembling peptide gel mapped to collagen-like adhesive network; ECM + division.",
    },
]
